name: Base Styles (Mainbar section)
description: Base settings for the Zeus theme
type: core

form:
  fields:

    dominant-color:
      type: input.colorpicker
      label: Dominant Color
      description: The dominant color of the site; it is used for links, menus, CTA, highlight backgrounds, titles and outlines .      
      default: "#0071bc"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      description: The color of the content
      default: "#212121"
    background:
      type: input.colorpicker
      label: Base Background Color
      description: The color of site's background; it is used in the mainbar section
      default: "#ffffff"
    background-image:
      type: input.imagepicker
      label: Background Image
      description: Select an image to be set as background in the Mainbar section
    content-margin:
      type: input.text
      label: Content Margin
      description: Specify the size of margin in rem, em or px units.      
      default: "0.5rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|px)'
    content-padding:
      type: input.text
      label: Content Padding
      description: Specify the size of padding in rem, em or px units.      
      default: "0.5rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|px)'