version: 2
preset:
  image: 'gantry-admin://layout/3column-equal.png'
  name: default
  timestamp: 1529047451
layout:
  /zenith/: {  }
  /navtop/: {  }
  /navigation/:
    -
      - 'logo-9501 25'
      - 'menu-6609 75'
  /header/: {  }
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - spacer-2395
      -
        'mainbar 50':
          -
            - system-messages-2617
      -
        'sidebar 25': {  }
  /mainbottom/: {  }
  /footertop/:
    -
      - 'custom-9805 25'
      - 'custom-7729 25'
      - 'position-module-8441 25'
      - 'position-module-1221 25'
  /footer/:
    -
      - 'logo-9571 21'
      - 'copyright-1736 26'
      - 'horizontalmenu-9034 24'
      - 'totop-8670 29'
    -
      - socialfloatingSZ-2700
  /footerbottom/: {  }
  /nadir/: {  }
  offcanvas:
    -
      - mobile-menu-5697
structure:
  zenith:
    type: section
    attributes:
      boxed: ''
  navtop:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: '0'
      class: ''
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
  features:
    type: section
    attributes:
      boxed: '2'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '0'
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
  footertop:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  footerbottom:
    type: section
    attributes:
      boxed: ''
  nadir:
    type: section
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '1'
      css3animation: '1'
content:
  logo-9501:
    title: 'Logo / Image'
  custom-9805:
    title: 'Discover Zeus'
    attributes:
      html: "<h3>Discover Zeus</h3>\n<p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu </p>"
  custom-7729:
    title: 'USEFUL LINKS'
    attributes:
      html: "<h3>Useful Links</h3>\n<ul>\n    <li><a href=\"#\">General Information</a></li>\n    <li><a href=\"#\">Discover Zeus Template</a></li>\n    <li><a href=\"#\">Learn from the best</a></li>\n    <li><a href=\"#\">Everyday inspiration</a></li>\n    <li><a href=\"#\">Check the demos</a></li>\n</ul>"
  position-module-8441:
    title: 'Module Instance'
    attributes:
      key: module-instance
  position-module-1221:
    title: 'Module Instance'
    attributes:
      key: module-instance
  logo-9571:
    title: 'Logo / Image'
  horizontalmenu-9034:
    title: 'Horizontal Menu'
  totop-8670:
    title: 'To Top'
  socialfloatingSZ-2700:
    title: 'Social Floating'
